version: '3.0'

services:

  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: kp-task-php
    restart: unless-stopped
    tty: true
    stdin_open: true
    ports:
      - "80:80"
    volumes:
      - .:/var/www/html
    working_dir: /var/www/html
    networks:
      - kp

networks:
  kp:
    driver: bridge
